apiVersion: v1
kind: Secret
metadata:
  name: 09-sectret
  namespace: desarrollo
data:
  password: TXkgc2VjcmV0IHBhc3N3b3JkLCBvdXRzaWRlIG9mIHRoZSBzb3VyY2UgY29kZS4gQmFzZTY0IGVuY29kZWQu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 03-deployment
  labels:
    app: spring-boot-app
  namespace: desarrollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: 01-pod
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: pod
          image: localhost:5000/k8s-springboot-app:latest
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 09-sectret
                  key: password
          envFrom:
            - configMapRef:
                name: 07-configmap-env
          volumeMounts:
            - name: my-volume
              mountPath: /volume-mount-path
            - name: configmap-volume
              mountPath: /etc/spring-boot-app
      volumes:
        - name: configmap-volume
          configMap:
            name: 07-configmap-file
        - name: my-volume
          persistentVolumeClaim:
            claimName: 07-persistentvolume-claim
