management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
config:
  variable: test